<?php

namespace AppBundle\Repository;

/**
 * DietRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietRepository extends \Doctrine\ORM\EntityRepository
{
}
