<?php

namespace AppBundle\Repository;

/**
 * DinnerSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinnerSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
